#! /bin/sh

# USAGE:
# import the entire file in your script
#   . ${file location}
# then use the log function
#   log ${level} ${message}

# import dependencies
COLORS_PATH="/usr/src/colors"
if [ -f ${COLORS_PATH} ]; then
  . ${COLORS_PATH}
else
  echo "${COLORS_PATH} doesn't exists, colors not available"
fi

# export constants
_TRACE="TRACE"
_DEBUG="DEBUG"
_INFO="INFO"
_WARN="WARN"
_ERROR="ERROR"

MIN_LOG_LEVEL=2


set_min_level() {
    tmp_min_level=$1
    if [ ${tmp_min_level} -ge 0 -a ${tmp_min_level} -le 4 ]; then
        MIN_LOG_LEVEL=${tmp_min_level}
    else
        log ${_WARN} "Cannot set min log level to $tmp_min_level"
    fi
}

log() (
    set_log_level() {
        LEVEL=$(echo "$1" | tr '[:lower:]' '[:upper:]')
        case ${LEVEL} in
            ${_TRACE} | ${_DEBUG})
                LOG_COLOR=${White}
                ;;
            ${_INFO})
                LOG_COLOR=${Cyan}
                ;;
            ${_WARN})
                LOG_COLOR=${Yellow}
                ;;
            ${_ERROR})
                LOG_COLOR=${Red}
                ;;
            *)
                log "WARN" "Log level $LEVEL not available, INFO level will be used"
                set_log_level "INFO"
                ;;
        esac
    }

    get_level_number() {
        input_level=$1
        case ${input_level} in
            ${_TRACE})
                echo 0
                ;;
            ${_DEBUG})
                echo 1
                ;;
            ${_INFO})
                echo 2
                ;;
            ${_WARN})
                echo 3
                ;;
            ${_ERROR})
                echo 4
                ;;
            *)
                log "WARN" "Log level $LEVEL_NUMBER not available, 2 (INFO) will be used"
                echo 2
                ;;
        esac
    }

    input_level=$1
    set_log_level ${input_level}
    MSG=$2

    LEVEL_NUMBER=$(get_level_number ${input_level})
    if [ ${LEVEL_NUMBER} -ge ${MIN_LOG_LEVEL} ]; then
        TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

        echo -e "${LOG_COLOR}${TIMESTAMP} [$LEVEL] ${MSG}${Color_Off}"
    fi

)

log_tra() {
  log ${_TRACE} $1
}

log_deb() {
  log ${_DEBUG} $1
}

log_inf() {
  log ${_INFO} $1
}

log_war() {
  log ${_WARN} $1
}

log_err() {
  log ${_ERROR} $1
}

demo() {
    # print only some level
    log ${_TRACE} "TRACE log"
    log ${_DEBUG} "DEBUG log"
    log ${_INFO} "INFO log"
    log ${_WARN} "WARN log"
    log ${_ERROR} "ERROR log"

    # print all level
    set_min_level 0
    log_tra "TRACE log"
    log_deb "DEBUG log"
    log_inf "INFO log"
    log_war "WARN log"
    log_err "ERROR log"
    set_min_level 2
}

demo
